// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"time"
)

type GameParticipant struct {
	ID      int64       `json:"id"`
	GameID  int64       `json:"game_id"`
	UserID  int64       `json:"user_id"`
	Foreign interface{} `json:"foreign"`
}

type GameResult struct {
	ID               int64     `json:"id"`
	RoomName         string    `json:"room_name"`
	WinningMovieID   string    `json:"winning_movie_id"`
	WinningMovieName string    `json:"winning_movie_name"`
	WinningVoteCount int64     `json:"winning_vote_count"`
	TotalPlayers     int64     `json:"total_players"`
	CompletedAt      time.Time `json:"completed_at"`
}

type RefreshToken struct {
	ID        int64     `json:"id"`
	UserID    int64     `json:"user_id"`
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID           int64     `json:"id"`
	Username     string    `json:"username"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type VoteEvent struct {
	ID        int64     `json:"id"`
	UserID    int64     `json:"user_id"`
	EventType string    `json:"event_type"`
	Action    string    `json:"action"`
	MovieID   string    `json:"movie_id"`
	MovieName string    `json:"movie_name"`
	CreatedAt time.Time `json:"created_at"`
}
