// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: vote_events.sql

package sqlcgen

import (
	"context"
)

const createVoteEvent = `-- name: CreateVoteEvent :one
INSERT INTO vote_events (
    user_id,
    event_type,
    action,
    movie_id,
    movie_name
) VALUES (?, ?, ?, ?, ?)
RETURNING id, user_id, event_type, "action", movie_id, movie_name, created_at
`

type CreateVoteEventParams struct {
	UserID    int64  `json:"user_id"`
	EventType string `json:"event_type"`
	Action    string `json:"action"`
	MovieID   string `json:"movie_id"`
	MovieName string `json:"movie_name"`
}

func (q *Queries) CreateVoteEvent(ctx context.Context, arg CreateVoteEventParams) (VoteEvent, error) {
	row := q.db.QueryRowContext(ctx, createVoteEvent,
		arg.UserID,
		arg.EventType,
		arg.Action,
		arg.MovieID,
		arg.MovieName,
	)
	var i VoteEvent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventType,
		&i.Action,
		&i.MovieID,
		&i.MovieName,
		&i.CreatedAt,
	)
	return i, err
}

const getVoteEventsByUser = `-- name: GetVoteEventsByUser :many
SELECT id, user_id, event_type, "action", movie_id, movie_name, created_at FROM vote_events
WHERE user_id = ?
ORDER BY created_at DESC
`

func (q *Queries) GetVoteEventsByUser(ctx context.Context, userID int64) ([]VoteEvent, error) {
	rows, err := q.db.QueryContext(ctx, getVoteEventsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VoteEvent{}
	for rows.Next() {
		var i VoteEvent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventType,
			&i.Action,
			&i.MovieID,
			&i.MovieName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
